# Project information
site_name: TYROS RPG
site_url: https://joemoose.github.io/tyros
site_author: Zachary Taylor

# Navigation
nav:
  - Home: README.md
  - 1 Make an Adventurer.md
  - 2 Equipment.md
  - 3 How to Play.md
  - 4 Appendix.md
  - 5 Credits.md

# Copyright
copyright: Copyright &copy; 2023 All rights reserved.

# Theme
theme:
  name: material
  logo: img/RPG-game.png
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - header.autohide
  font:
    text: Merriweather
    Code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  generator: true